### ISSUE TITLE
Currently Failing Suite Tests

### ISSUE THREAD

**Issue by ingydotnet** [flyx/NimYAML#104]
Happy New Year, my friend!

Here's a small gift for you ;)

* `4EJS` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/4EJS.yaml) [Play](https://play.yaml.io/main/parser?input=LS0tCmE6CgliOgoJCWM6IHZhbHVlCg==)
* `9JBA` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/9JBA.yaml) [Play](https://play.yaml.io/main/parser?input=LS0tClsgYSwgYiwgYywgXSNpbnZhbGlkCg==)
* `9MAG` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/9MAG.yaml) [Play](https://play.yaml.io/main/parser?input=LS0tClsgLCBhLCBiLCBjIF0K)
* `CTN5` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/CTN5.yaml) [Play](https://play.yaml.io/main/parser?input=LS0tClsgYSwgYiwgYywgLCBdCg==)
* `CVW2` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/CVW2.yaml) [Play](https://play.yaml.io/main/parser?input=LS0tClsgYSwgYiwgYywjaW52YWxpZApdCg==)
* `DK4H` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/DK4H.yaml) [Play](https://play.yaml.io/main/parser?input=LS0tClsga2V5CiAgOiB2YWx1ZSBdCg==)
* `DK95-01` [Suite](https://github.com/yaml/yaml-test-suite/blob/new-tests-jan-3/src/DK95.yaml) [Play](https://play.yaml.io/main/parser?input=Zm9vOiAiYmFyCgliYXoiCg==)
* `DK95-03` [Suite](https://github.com/yaml/yaml-test-suite/blob/new-tests-jan-3/src/DK95.yaml) [Play](https://play.yaml.io/main/parser?input=IAkKZm9vOiAxCg==)
* `DK95-04` [Suite](https://github.com/yaml/yaml-test-suite/blob/new-tests-jan-3/src/DK95.yaml) [Play](https://play.yaml.io/main/parser?input=Zm9vOiAxCgkKYmFyOiAyCg==)
* `DK95-06` [Suite](https://github.com/yaml/yaml-test-suite/blob/new-tests-jan-3/src/DK95.yaml) [Play](https://play.yaml.io/main/parser?input=Zm9vOgogIGE6IDEKICAJYjogMgo=)
* `DK95-07` [Suite](https://github.com/yaml/yaml-test-suite/blob/new-tests-jan-3/src/DK95.yaml) [Play](https://play.yaml.io/main/parser?input=JVlBTUwgMS4yCgkKLS0tCg==)
* `JEF9-02` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/JEF9.yaml) [Play](https://play.yaml.io/main/parser?input=LSB8KwogICA=)
* `MUS6-01` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/MUS6.yaml) [Play](https://play.yaml.io/main/parser?input=JVlBTUwgMS4yCi0tLQolWUFNTCAxLjIKLS0tCg==)
* `QB6E` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/QB6E.yaml) [Play](https://play.yaml.io/main/parser?input=LS0tCnF1b3RlZDogImEKYgpjIgo=)
* `SU5Z` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/SU5Z.yaml) [Play](https://play.yaml.io/main/parser?input=a2V5OiAidmFsdWUiIyBpbnZhbGlkIGNvbW1lbnQK)
* `UKK6-02` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/UKK6.yaml) [Play](https://play.yaml.io/main/parser?input=IQo=)
* `Y79Y-02` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/Y79Y.yaml) [Play](https://play.yaml.io/main/parser?input=LSBbCgkKIGZvbwogXQo=)
* `Y79Y-04` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/Y79Y.yaml) [Play](https://play.yaml.io/main/parser?input=LQktCg==)
* `Y79Y-05` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/Y79Y.yaml) [Play](https://play.yaml.io/main/parser?input=LSAJLQo=)
* `ZXT5` [Suite](https://github.com/yaml/yaml-test-suite/blob/main/src/ZXT5.yaml) [Play](https://play.yaml.io/main/parser?input=WyAia2V5IgogIDp2YWx1ZSBdCg==)

Also you might we interested in the new productions in progress here:
https://spec.yaml.io/main/spec/1.3.0/#rule-yaml-stream

They are equivalent to the 1.2.2 productions but better named and much less of them.

Drop by https://matrix.to/#/#chat:yaml.io and say Hi sometime. We miss you.

**Comment by flyx** [comment]
I finally found time to address these, tests are all green again.
