### ISSUE TITLE
broken enum

### ISSUE THREAD

**Issue by zhenyamega** [flyx/NimYAML#110]
# 1.

This object "Data" detection as Map

```nim
import yaml/serialization, streams

type
    Data = object
        data: string

var node: Data

let s = newFileStream("in.yaml")
load(s, node)
s.close()
```
but this object "Data" detection as Seq

```nim
import yaml/serialization, streams

type
    DataType = enum
        Default
        Sequence

    Data = object
        data: string
        case kind: DataType
        of Default: value: string
        of Sequence: valueSeq: seq[string]

var node: Data

let s = newFileStream("in.yaml")
load(s, node)
s.close()
```

error: `Error: unhandled exception: While constructing Data: Expected yamlStartSeq, got yamlStartMap [YamlConstructionError]`

Why did it become a sequence?

# 2.

with 1 enum we can work

**main.nim**

```nim
import yaml/serialization, streams

type
    DataType = enum
        Default
        Sequence

    Data = object
        data: string
        case kind: DataType
        of Default: value: string
        of Sequence: valueSeq: seq[string]

var node: Data

let s = newFileStream("in.yaml")
load(s, node)
s.close()

echo node.value
```

**in.yaml**

```yml
- data: test
- kind: Default
- value: test
```

It work and output `test`

but with 2 enum

**main.nim**

```nim
import yaml/serialization, streams

type
    DataType = enum
        Default
        Sequence

    Data = object
        data: string
        case kind1 : DataType
        of Default: value1: string
        of Sequence: valueSeq1: seq[string]
        case kind2 : DataType
        of Default: value2: string
        of Sequence: valueSeq2: seq[string]

var node: Data

let s = newFileStream("in.yaml")
load(s, node)
s.close()

echo node.value1
```

**in.yaml**

```yml
- data: test
- kind1: Default
- value1: test
- kind2: Default
- value2: test
```

error `/root/.nimble/pkgs/yaml-0.16.0/yaml/serialization.nim(739, 16) Error: Unexpected kind of field 'kind2': nnkRecCase`

**Comment by flyx** [comment]
See the [docs on variant object types](https://nimyaml.org/serialization.html#variant-object-types)? Specifically this:

> The value of a discriminator field must be loaded before any value of a field that depends on it. Therefore, a YAML mapping cannot be used to serialize variant object types - the YAML specification explicitly states that the order of key-value pairs in a mapping must not be used to convey content information. So, any variant object type is serialized as a list of key-value pairs.

This should answer 1.

Concerning 2, multiple `case` constructs in an object are currently not supported. I am not entirely sure why, since it has been a long time since I wrote that code. I can't promise a timely fix but suggest you have a look at  `{.implicit.}` and check if that can solve your problem. Your example would become:

```nim
import yaml/serialization, streams

type
    DataType = enum
        Default
        Sequence

    Inner1 {.implicit.} = object
        case kind: DataType
        of Default: value: string
        of Sequence: valueSeq: seq[string]

    Inner2 {.implicit.} = object
        case kind : DataType
        of Default: value: string
        of Sequence: valueSeq: seq[string]

    Data = object
        data: string
        inner1: Inner1
        inner2: Inner2

setTag(seq[string], "!list".Tag)

var node: Data

let s = newFileStream("in.yaml")
load(s, node)
s.close()
```

This can load the following YAML:

```yaml
data: test
inner1: test # sets kind to Default and value to "test"
inner2: !list [test2, test3] # sets kind to Sequence.
```

**Comment by flyx** [comment]
That `Config` type is loadable but you must put the fields in a sequence for the reason quoted above from the docs. It's either that or use an implicit type and wrap the inner params into objects.
