### ISSUE TITLE
defaultVal is not observed on stropped names

### ISSUE THREAD

**Issue by sungchul-twinny** [flyx/NimYAML#116]
type PathDocument = ref object
  `$ref` {.defaultVal: none(string).}: Option[string]
  others {.defaultVal: none(string).}: Option[string]

Hello.
First of all, Thank you for your awesome package!
While I am using NimYAML, I observed the above object always get missing '$ref' error dispite the fact that I already set the defaultVal.

Is this a known issue?

Thank you.

**Comment by flyx** [comment]
Has been fixed in Nim compiler.
