### ISSUE TITLE
Nim CI is broken 

### ISSUE THREAD

**Issue by jmgomez** [flyx/NimYAML#139]
Hi, 
Due to a recent change on this repo the Nim CI is broken see: 

https://github.com/nim-lang/Nim/actions/runs/6030450857/job/16362292729?pr=22513

```
 Error: cannot open 'test/tserialization.nim'
  
  FAILURE
  FAIL: PackageFileParsed c                                          (766.31 sec)
  Test "PackageFileParsed" in category "nimble-packages"
  Failure: reBuildFailed
  
 ```

**Comment by flyx** [comment]
Sorry, that has already been fixed in 879c7ad
