### ISSUE TITLE
The load function breaks for me when compiling with Nim v2.2.0

### ISSUE THREAD

**Issue by jfilby** [flyx/NimYAML#145]
You can see my description on the Nim forum: https://forum.nim-lang.org/t/12620

This is surely a bug with the Nim compiler, but I'm not sure if the yaml library can workaround it.

**Comment by flyx** [comment]
Unless there's a compiler version where this works, it's more likely this is an actual NimYAML bug. `ref` objects have dedicated handling in NimYAML, so the actual loading code generated by calling the generic `load` function looks quite different depending on whether some type is a `ref` or not.

I'll investigate.

**Comment by flyx** [comment]
Can you give the contents of the YAML file you're loading?

**Comment by jfilby** [comment]
It fails when compiling, so its likely the compiler that's at fault. It seems to be if the object to load, or any part of it, is a ref object. Should I close this issue then?

**Comment by flyx** [comment]
Ah, missed that. Can still be NimYAML since it employs a lot of macros which execute at compile time. Leave it open, I want to have a closer look before labelling it as compiler bug.

**Comment by flyx** [comment]
Compiles with Nim 2.0.2.

Nim 2.2.0 seems to be thoroughly broken, not even the tests execute with `nim test`.

Since this project is not that active, it doesn't regularly test against updated Nim versions. Would need a bisect on Nim to check when exactly it broke.

While it seems to be a compiler bug, let's leave this issue open as long as the compiler bug isn't fixed – it could be that NimYAML can do a workaround.

It's unlikely that I will find time to do a proper analysis before the year ends.

**Comment by jfilby** [comment]
Perhaps a test, created from a minimal reproducible program, should be submitted to the Nim compiler repo for CI/CD? Since the yaml library is in the standard lib it could be a high-level test such as the case for this issue?

**Comment by flyx** [comment]
I was under the impression that Nim did regular tests against commonly used libs including NimYAML to prevent such an issue, but that does not seem the case (anymore?).

In my experience, the Nim team does quite fine with bug reports such as this one. I'm unfortunately quite occupied currently, but if you want to file this yourself, you can:

 * check which release versions between 2.0.2 and 2.2.0 are affected
 * open an issue with the Nim compiler containing your code example and the information gathered

**Comment by jfilby** [comment]
OK I've done that, thanks for your input.

Nim compiler issue: https://github.com/nim-lang/Nim/issues/24526

**Comment by jfilby** [comment]
Hi, someone has reviewed the Nim compiler issue I opened and done an analysis. It sounds like the crash could be averted in the yaml lib. Ideally the compiler code would also be updated to prevent a crash and just return an error.

**Comment by jfilby** [comment]
The issue has been closed on the Nim compiler side.
