### ISSUE TITLE
Cannot compile program where load() called on Point2d

### ISSUE THREAD

**Issue by mcclure** [flyx/NimYAML#15]
I have yaml [0.5.1] installed from nimble and I am running with a Nim self-built from git 07d7d35d99526283.

I run the following program

    import basic2d, yaml

    var pointList: seq[Point2D]
    var f = newFileStream("points.yaml")
    load(f, pointList)
    f.close()

This program fails to compile, as does any other program where I load() on a structure containing Point2Ds. By contrast, calling dump() on these structures works fine. The error is

    $ nim compile test.nim
    Hint: system [Processing]
    Hint: test [Processing]
    Hint: basic2d [Processing]
    Hint: math [Processing]
    Hint: strutils [Processing]
    Hint: parseutils [Processing]
    Hint: yaml [Processing]
    Hint: streams [Processing]
    Hint: unicode [Processing]
    Hint: lexbase [Processing]
    Hint: tables [Processing]
    Hint: hashes [Processing]
    Hint: etcpriv [Processing]
    Hint: json [Processing]
    Hint: macros [Processing]
    Hint: queues [Processing]
    Hint: typetraits [Processing]
    test.nim(5, 5) template/generic instantiation from here
    c:\users\andi\.nimble\pkgs\yaml-0.5.1\private\serialization.nim(789, 17) template/generic instantiation from here
    c:\users\andi\.nimble\pkgs\yaml-0.5.1\private\serialization.nim(770, 19) template/generic instantiation from here
    c:\users\andi\.nimble\pkgs\yaml-0.5.1\private\serialization.nim(645, 18) template/generic instantiation from here
    c:\users\andi\.nimble\pkgs\yaml-0.5.1\private\serialization.nim(218, 19) template/generic instantiation from here
    c:\users\andi\.nimble\pkgs\yaml-0.5.1\private\serialization.nim(614, 20) template/generic instantiation from here
    c:\users\andi\.nimble\pkgs\yaml-0.5.1\private\serialization.nim(468, 30) template/generic instantiation from here
    c:\msys64\home\andi\work\g\nim\lib\pure\basic2d.nim(71, 7) template/generic instantiation from here
    c:\users\andi\.nimble\pkgs\yaml-0.5.1\private\serialization.nim(614, 20) template/generic instantiation from here
    c:\users\andi\.nimble\pkgs\yaml-0.5.1\private\serialization.nim(140, 22) template/generic instantiation from here
    c:\users\andi\.nimble\pkgs\yaml-0.5.1\private\serialization.nim(143, 48) Error: type mismatch: got (string)
    but expected one of:
    proc parseBiggestFloat(s: string; number: var BiggestFloat; start = 0): int

**Comment by flyx** [comment]
Has probably been fixed along with #17. Can you try and build against devel?

**Comment by flyx** [comment]
Just tried it, compiles fine now on devel.
