### ISSUE TITLE
Error: can raise an unlisted exception

### ISSUE THREAD

**Issue by andreaferretti** [flyx/NimYAML#19]
Apparently, this arises when trying to serialize anything that contains a table. A small example would be

```nim
import streams, yaml, tables

var
  t = {"a": "b"}.newTable()
  s = newFileStream("test.yaml", fmWrite)
dump(t, s)
s.close()
```

It seems that this happens because `representChild` is explicit defined not to raise exceptions, but accessing table keys can raise `KeyError`.

I think one should either catch that exception, or remove the explicit pragma `{. raises: [] .}` and let the compiler infer effects

**Comment by flyx** [comment]
Yeah, exception handling seems to have been improved a bit since 0.13.1 and detects thing it didn't when I wrote the code :). I'll fix it tomorrow.

**Comment by flyx** [comment]
This is an interesting one. I do not see how the source line the compiler complains about can raise this exception, and I also cannot wrap it with try/catch - the compiler still complains.

Accessing table keys is done with the `pairs` iterator which does not yield a `KeyError`.

Might be a compiler regression, or something so subtle I did not find it yet. I do not want to lose the guarantee `{. raises [] .}` everywhere. Will need some time to figure it out.

**Comment by flyx** [comment]
This was one badass bug.
