### ISSUE TITLE
Library is broken on devel

### ISSUE THREAD

**Issue by andreaferretti** [flyx/NimYAML#20]
Just wanted to let you know that the library does not work on the devel branch anymore. You may want to open a suitable issue on Nim for this.

An example that does not compile is:

```nim
import yaml

type Foo = object
  a: int

var
  s = newFileStream("test.yaml", fmRead)
  c: Foo
load(s, c)
s.close()
```

**Comment by flyx** [comment]
Seems to be a duplicate of #19 *sigh*. I have not yet found the root cause of that.

**Comment by andreaferretti** [comment]
It does not seem to be a duplicate. I only got this error since this morning; moreover it happens on types not containing tables, unlike #19. Finally, it gives a different error message (`node has no type`). It seems more plausible that Nim has broken something in the way types are handled in macros

**Comment by flyx** [comment]
Can you please give the complete error message and stacktrace that you get from the code? I get

    lib/pure/collections/queues.nim(70, 7) Error: can raise an unlisted exception: ref IndexError

With Nim devel updated just half an hour ago.

**Comment by andreaferretti** [comment]
I get

```
stack trace: (most recent call last)
/home/papillon/.nimble/pkgs/yaml-0.6.1/private/serialization.nim(462)
/home/papillon/.nimble/pkgs/yaml-0.6.1/private/serialization.nim(462)(450) isVariantObject
test.nim(9, 5) template/generic instantiation from here
/home/papillon/.nimble/pkgs/yaml-0.6.1/private/serialization.nim(462)(450) isVariantObject(823, 17) template/generic instantiation from here
/home/papillon/.nimble/pkgs/yaml-0.6.1/private/serialization.nim(462)(450) isVariantObject(804, 19) template/generic instantiation from here
/home/papillon/.nimble/pkgs/yaml-0.6.1/private/serialization.nim(462)(450) isVariantObject(648, 20) template/generic instantiation from here
/home/papillon/.nimble/pkgs/yaml-0.6.1/private/serialization.nim(462)(450) isVariantObject(450, 22) Error: node has no type
```

with latest nim devel. I am not sure why you get a different error

**Comment by flyx** [comment]
Interesting. Can you test whether `nim tests` runs in NimYAML for you? For me, that raises the same error as I get here.

**Comment by andreaferretti** [comment]
Doint `nim tests` on the repo I still get

```
stack trace: (most recent call last)
private/serialization.nim(462)
private/serialization.nim(450) isVariantObject
test/serializing.nim(78, 7) template/generic instantiation from here
test/serializing.nim(190, 8) template/generic instantiation from here
test/serializing.nim(193, 9) template/generic instantiation from here
private/serialization.nim(823, 17) template/generic instantiation from here
private/serialization.nim(804, 19) template/generic instantiation from here
private/serialization.nim(648, 20) template/generic instantiation from here
private/serialization.nim(361, 19) template/generic instantiation from here
private/serialization.nim(648, 20) template/generic instantiation from here
private/serialization.nim(450, 22) Error: node has no type
```

**Comment by flyx** [comment]
Okay, I will dig into it. Thanks for the infos.

**Comment by flyx** [comment]
Okay, I was on the wrong branch earlier, shame on me. I reported this to Nim:

https://github.com/nim-lang/Nim/issues/4462

**Comment by andreaferretti** [comment]
Seems fixed upstream, so I can close this now

**Comment by flyx** [comment]
\o/
