### ISSUE TITLE
Undeclared identifier: parseBiggestFloat

### ISSUE THREAD

**Issue by J0eCool** [flyx/NimYAML#30]
Reproducing code:
```nim
import yaml.serialization, streams
type Vec* = tuple[x, y: float]

var v = (x: 40.0, y: 50.0)
var s = newFileStream("out.yaml")
load(s, v)
s.close()
echo "v = <", v.x, ", ", v.y, ">"
```

This fails with `[path\to\]yaml-0.8.0\yaml\serialization.nim(270, 15) Error: undeclared identifier: 'parseBiggestFloat'`

It seems that `parseBiggestFloat` can be found in the `parseutils` module, whereas NimYAML only includes `strutils`, which has `parseBiggestInt`.
It would probably be good to add a regression test to `tserialization.nim`, which doesn't seem to test any floats.

**Comment by flyx** [comment]
Strange, I thought this has already been addressed in #17 . Maybe a regression from restructuring in 0.7.0.

**Comment by yawnt** [comment]
I'm having the same issue when I try to install it

```
~/.nimble/pkgs/yaml-0.8.0/yaml/serialization.nim(270, 15) Error: undeclared identifier: 'parseBiggestFloat'
```

would it be possible to publish a new version with the fix?
Thanks!

**Comment by flyx** [comment]
Version 0.9.0 is out.
