### ISSUE TITLE
Add reference to YAML website.

### ISSUE THREAD

**Issue by Varriount** [flyx/NimYAML#32]
NimYAML is currently not on the [current list of YAML libraries](http://yaml.org/) on the official YAML website.

**Comment by flyx** [comment]
Yeah, because I did not properly setup a HTTPS-Domain for it yet. Thanks for reminding me, I did that now.

Will be fixed with yaml/yaml-org-site#16

**Comment by flyx** [comment]
NimYAML is now linked on the official site (even though my PR isn't in master yet).
