### ISSUE TITLE
More control when loading objects / Merely extending objects

### ISSUE THREAD

**Issue by davidnorthetal** [flyx/NimYAML#43]
Currently it seems whenever I load a single object from a file that specifies additional fields that don't correspond to any of the object an exception is thrown and it aborts.

I'm within a use-case where I wouldn't mind excessive fields in the file tho and would rather just skip them and proceed with loading whatever fields do fit.

AFAIS there's currently no way to achieve this.

**Comment by flyx** [comment]
Does [`ignoreInputKey`](https://nimyaml.org/yaml.serialization.html#ignoreInputKey.m,typedesc,) help you?

**Comment by davidnorthetal** [comment]
Thanks for the quick response!

However, this would require me to know the fields names in advance, no? - I don't know them tho. People might just add arbitrary ones.

**Comment by flyx** [comment]
Well then we need an `ignoreUnknownKeys` :). I'll need to have a look whether that is easily implementable with the current compile-time infrastructure in the `serialization` module.

**Comment by flyx** [comment]
Things to do:

 * Provide a macro `ignoreUnknownKey`
 * Implement it for tuples ([code pointer](https://github.com/flyx/NimYAML/blob/devel/yaml/serialization.nim#L867))
 * Implement it for objects ([code pointer](https://github.com/flyx/NimYAML/blob/devel/yaml/serialization.nim#L803))

I'll try to allocate time to do this, it seems like a useful addition. However, it's not trivial and may take some time.
