### ISSUE TITLE
Version currently in nimble not support by nim 0.17.3. Could you make a new version?

### ISSUE THREAD

**Issue by treeform** [flyx/NimYAML#51]
```
/Users/me/.nimble/pkgs/yaml-0.10.3/yaml/private/lex.nim(1160, 9) template/generic instantiation from here
/Users/me/.nimble/pkgs/yaml-0.10.3/yaml/private/lex.nim(1142, 36) template/generic instantiation from here
/Users/me/.nimble/pkgs/yaml-0.10.3/yaml/private/lex.nim(1069, 11) Error: illegal capture 'peek'
```

Has been fixed on github but not if you install with nimble.

**Comment by dom96** [comment]
``nimble install yaml@#head``

**Comment by flyx** [comment]
What @dom96 said. In general, I do release fixes for bugs with stable Nim quickly, but when you use a Nim devel version, expect the need for using the NimYAML devel version as well. I release when I see a benefit for Nim stable and won't craft a release for every bug fixed.
