### ISSUE TITLE
Error: enable the 'not nil' annotation with {.experimental: "notnil".}

### ISSUE THREAD

**Issue by majj** [flyx/NimYAML#58]
for Nim 0.18.1:

.nimble\pkgs\yaml-0.10.3\yaml\stream.nim(140, 31) Error: enable the 'not nil' annotation with {.experimental: "notnil".}

**Comment by majj** [comment]
add:
·
when defined(nimNoNil):
    {.experimental: "notnil".}
·
on the top of following files:
dom.nim
parser.nim
stream.nim

**Comment by dom96** [comment]
PR?

**Comment by flyx** [comment]
Fixed by #59
