### ISSUE TITLE
Cannot construct to int32: 0; error: index out of bounds

### ISSUE THREAD

**Issue by alehander92** [flyx/NimYAML#60]
I have a weird error: I can't seem to load 0

```yaml
%YAML 1.2
number: 0
```
```nim
import yaml.serialization, streams, os

type 
  Value = object
    number: int

var raw = newFileStream("a.yaml", fmRead)
var value: Value
load(raw, value)
echo value
```

If I run this on the yaml, I get the error. If I change number to anything != 0 it seems to work

Is it a known problem and is it easy to fix ? I use nim devel(> 0.18.1)

**Comment by flyx** [comment]
Not a known problem. Can you provide a stacktrace of the error?

**Comment by alehander42** [comment]
sorry for not debugging it immeditely, it's a simple fix

https://github.com/flyx/NimYAML/pull/61
