### ISSUE TITLE
"test/yaml-test-suite" submodule broken by upstream

### ISSUE THREAD

**Issue by stefantalpalaru** [flyx/NimYAML#77]
```text
$ git submodule update --recursive --init
Submodule 'test/yaml-test-suite' (https://github.com/yaml/yaml-test-suite.git) registered for path 'test/yaml-test-suite'
Cloning into '/mnt/sda3/storage/CODE/status/NimYAML/test/yaml-test-suite'...
error: Server does not allow request for unadvertised object fa266d172ef7b2cdd35219b8e677fa5e0ae86269
Fetched in submodule path 'test/yaml-test-suite', but it did not contain fa266d172ef7b2cdd35219b8e677fa5e0ae86269. Direct fetching of that commit failed.
```

Upstream issue: https://github.com/yaml/yaml-test-suite/issues/51

**Comment by flyx** [comment]
submodule was always a pain, should probably switch to git-subrepo so that upstream can't break it…

**Comment by stefantalpalaru** [comment]
As long as you target a certain commit and upstream decides to make that commit disappear, there's nothing you can do to prevent it.

**Comment by flyx** [comment]
git-subrepo will put an actual clone of upstream into this repository. If a commit vanishes upstream, it may be tricky to update the clone but that would only affect maintainers. Users will still be able to clone this repo with the currently cloned state and thus not be affected by upstream, which is the goal.

**Comment by keslerm** [comment]
Is there a workaround for this atm?

**Comment by flyx** [comment]
I changed the commit reference to a release tag, they surely won't break those.
